cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

language: php

# Declare versions of PHP to use.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - "7.4snapshot"

env:
  global:
    - WP_VERSION=master # Git equivalent of SVN /trunk

matrix:
  allow_failures:
  - php: "7.4snapshot"

  fast_finish: true

# Before install, failures in this section will result in build status 'errored'
before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  # clone the WordPress develop repo
  - WP_DEVELOP_DIR=/tmp/wordpress
  - git clone --depth=1 --branch="master" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then composer require phpunit/phpunit:^7; fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost master
